create table IF NOT EXISTS member_main (member_no long generated by default as identity
                                       , nickname varchar(255)
                                       , sex char(1)
                                       , is_instructor boolean);

create table IF NOT EXISTS class_main (class_no long generated by default as identity
                                      , title varchar(255))