create table IF NOT EXISTS member_main (
    member_no long generated by default as identity,
    nickname varchar(255),
    sex char(1),
    is_instructor boolean,
    primary key (member_no)
);

create table IF NOT EXISTS class_main (
    class_no long generated by default as identity,
    title varchar(255),
    status char(2),
    genre char(1),
    region char(2),
    instructor_no_1 long,
    instructor_no_2 long,
    location varchar(255),
    price decimal,
    primary key (class_no)
);

create table IF NOT EXISTS class_schedule (
    seq long generated by default as identity,
    class_no BIGINT,
    start_date datetime,
    end_date datetime,
    primary key (seq)
);

create table IF NOT EXISTS class_discount (
    seq long generated by default as identity,
    class_no long,
    discount_type char(1),
    discount_condition varchar(255),
    discount_amount decimal,
    primary key (seq)
);

create table IF NOT EXISTS class_notice (
    seq long generated by default as identity,
    class_no long,
    notice_type char(1),
    notice varchar(255),
    primary key (seq)
);

create table IF NOT EXISTS class_contact (
    seq long generated by default as identity,
    class_no long,
    member_no long,
    contact_type char(1),
    contact varchar(255),
    primary key (seq)
);
