create table IF NOT EXISTS member_main (
    member_no int generated by default as identity, -- auto_increment,
    nickname varchar(255),
    sex char(1),
    is_instructor boolean,
    primary key (member_no)
);

create table IF NOT EXISTS member_contact (
    seq int generated by default as identity, -- auto_increment,
    member_no int,
    contact_type char(1),
    contact varchar(255),
    primary key (seq),
    foreign key (member_no) references member_main (member_no)
);

create table IF NOT EXISTS class_main (
    class_no int generated by default as identity, -- auto_increment,
    title varchar(255),
    class_image varchar(255),
    status char(2),
    genre char(1),
    region char(2),
    instructor_no_1 int,
    instructor_no_2 int,
    start_date datetime,
    end_date datetime,
    date_desc varchar(255),
    start_time char(5),
    end_time char(5),
    time_desc varchar(255),
    location varchar(255),
    price decimal,
    account varchar(255),
    primary key (class_no),
    foreign key (instructor_no_1) references member_main (member_no),
    foreign key (instructor_no_2) references member_main (member_no)
);

create table IF NOT EXISTS class_discount (
    seq int generated by default as identity, -- auto_increment,
    class_no int,
    discount_type char(1),
    discount_text varchar(255),
    discount_date_condition datetime,
    discount_class_condition varchar(255),
    discount_amount decimal,
    primary key (seq),
    foreign key (class_no) references class_main (class_no)
);

create table IF NOT EXISTS class_notice (
    seq int generated by default as identity, -- auto_increment,
    class_no int,
    notice_type char(1),
    notice varchar(255),
    primary key (seq),
    foreign key (class_no) references class_main (class_no)
);

create table IF NOT EXISTS class_contact (
    seq int generated by default as identity, -- auto_increment,
    class_no int,
    member_no int,
    contact_type char(1),
    contact varchar(255),
    primary key (seq),
    foreign key (class_no) references class_main (class_no)
);
